package life.majiang.community.model;

public class Accesstoken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesstoken.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accesstoken.access_token
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String accessToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesstoken.id
     *
     * @return the value of accesstoken.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesstoken.id
     *
     * @param id the value for accesstoken.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accesstoken.access_token
     *
     * @return the value of accesstoken.access_token
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accesstoken.access_token
     *
     * @param accessToken the value for accesstoken.access_token
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }
}