package life.majiang.community.model;

public class Autoactiondo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autoactiondo.id
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autoactiondo.action_id
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    private Long actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autoactiondo.location
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autoactiondo.click_count
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    private String clickCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autoactiondo.lor
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    private String lor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autoactiondo.content
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autoactiondo.interval
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    private String interval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autoactiondo.id
     *
     * @return the value of autoactiondo.id
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autoactiondo.id
     *
     * @param id the value for autoactiondo.id
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autoactiondo.action_id
     *
     * @return the value of autoactiondo.action_id
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public Long getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autoactiondo.action_id
     *
     * @param actionId the value for autoactiondo.action_id
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autoactiondo.location
     *
     * @return the value of autoactiondo.location
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autoactiondo.location
     *
     * @param location the value for autoactiondo.location
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autoactiondo.click_count
     *
     * @return the value of autoactiondo.click_count
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public String getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autoactiondo.click_count
     *
     * @param clickCount the value for autoactiondo.click_count
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public void setClickCount(String clickCount) {
        this.clickCount = clickCount == null ? null : clickCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autoactiondo.lor
     *
     * @return the value of autoactiondo.lor
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public String getLor() {
        return lor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autoactiondo.lor
     *
     * @param lor the value for autoactiondo.lor
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public void setLor(String lor) {
        this.lor = lor == null ? null : lor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autoactiondo.content
     *
     * @return the value of autoactiondo.content
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autoactiondo.content
     *
     * @param content the value for autoactiondo.content
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autoactiondo.interval
     *
     * @return the value of autoactiondo.interval
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public String getInterval() {
        return interval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autoactiondo.interval
     *
     * @param interval the value for autoactiondo.interval
     *
     * @mbg.generated Tue Sep 01 11:21:31 CST 2020
     */
    public void setInterval(String interval) {
        this.interval = interval == null ? null : interval.trim();
    }
}