package life.majiang.community.model;

public class Commongood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.common_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long commonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.user_name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.creat_gmt
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long creatGmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.up_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long upId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.question_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.readflag
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Integer readflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commongood.content
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.id
     *
     * @return the value of commongood.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.id
     *
     * @param id the value for commongood.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.common_id
     *
     * @return the value of commongood.common_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getCommonId() {
        return commonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.common_id
     *
     * @param commonId the value for commongood.common_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setCommonId(Long commonId) {
        this.commonId = commonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.user_id
     *
     * @return the value of commongood.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.user_id
     *
     * @param userId the value for commongood.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.user_name
     *
     * @return the value of commongood.user_name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.user_name
     *
     * @param userName the value for commongood.user_name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.creat_gmt
     *
     * @return the value of commongood.creat_gmt
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getCreatGmt() {
        return creatGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.creat_gmt
     *
     * @param creatGmt the value for commongood.creat_gmt
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setCreatGmt(Long creatGmt) {
        this.creatGmt = creatGmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.up_id
     *
     * @return the value of commongood.up_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getUpId() {
        return upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.up_id
     *
     * @param upId the value for commongood.up_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setUpId(Long upId) {
        this.upId = upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.question_id
     *
     * @return the value of commongood.question_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.question_id
     *
     * @param questionId the value for commongood.question_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.readflag
     *
     * @return the value of commongood.readflag
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Integer getReadflag() {
        return readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.readflag
     *
     * @param readflag the value for commongood.readflag
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setReadflag(Integer readflag) {
        this.readflag = readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commongood.content
     *
     * @return the value of commongood.content
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commongood.content
     *
     * @param content the value for commongood.content
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}