package life.majiang.community.model;

public class Doautoaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doautoaction.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doautoaction.action_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doautoaction.location
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doautoaction.click_count
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String clickCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doautoaction.lor
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String lor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doautoaction.content
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doautoaction.jian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String jian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doautoaction.tuotime
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String tuotime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doautoaction.id
     *
     * @return the value of doautoaction.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doautoaction.id
     *
     * @param id the value for doautoaction.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doautoaction.action_id
     *
     * @return the value of doautoaction.action_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doautoaction.action_id
     *
     * @param actionId the value for doautoaction.action_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doautoaction.location
     *
     * @return the value of doautoaction.location
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doautoaction.location
     *
     * @param location the value for doautoaction.location
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doautoaction.click_count
     *
     * @return the value of doautoaction.click_count
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doautoaction.click_count
     *
     * @param clickCount the value for doautoaction.click_count
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setClickCount(String clickCount) {
        this.clickCount = clickCount == null ? null : clickCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doautoaction.lor
     *
     * @return the value of doautoaction.lor
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getLor() {
        return lor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doautoaction.lor
     *
     * @param lor the value for doautoaction.lor
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setLor(String lor) {
        this.lor = lor == null ? null : lor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doautoaction.content
     *
     * @return the value of doautoaction.content
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doautoaction.content
     *
     * @param content the value for doautoaction.content
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doautoaction.jian
     *
     * @return the value of doautoaction.jian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getJian() {
        return jian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doautoaction.jian
     *
     * @param jian the value for doautoaction.jian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setJian(String jian) {
        this.jian = jian == null ? null : jian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doautoaction.tuotime
     *
     * @return the value of doautoaction.tuotime
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getTuotime() {
        return tuotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doautoaction.tuotime
     *
     * @param tuotime the value for doautoaction.tuotime
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setTuotime(String tuotime) {
        this.tuotime = tuotime == null ? null : tuotime.trim();
    }
}