package life.majiang.community.model;

import java.util.ArrayList;
import java.util.List;

public class DoautoactionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public DoautoactionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andActionIdIsNull() {
            addCriterion("action_id is null");
            return (Criteria) this;
        }

        public Criteria andActionIdIsNotNull() {
            addCriterion("action_id is not null");
            return (Criteria) this;
        }

        public Criteria andActionIdEqualTo(Long value) {
            addCriterion("action_id =", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotEqualTo(Long value) {
            addCriterion("action_id <>", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdGreaterThan(Long value) {
            addCriterion("action_id >", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("action_id >=", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLessThan(Long value) {
            addCriterion("action_id <", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLessThanOrEqualTo(Long value) {
            addCriterion("action_id <=", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdIn(List<Long> values) {
            addCriterion("action_id in", values, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotIn(List<Long> values) {
            addCriterion("action_id not in", values, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdBetween(Long value1, Long value2) {
            addCriterion("action_id between", value1, value2, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotBetween(Long value1, Long value2) {
            addCriterion("action_id not between", value1, value2, "actionId");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andClickCountIsNull() {
            addCriterion("click_count is null");
            return (Criteria) this;
        }

        public Criteria andClickCountIsNotNull() {
            addCriterion("click_count is not null");
            return (Criteria) this;
        }

        public Criteria andClickCountEqualTo(String value) {
            addCriterion("click_count =", value, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountNotEqualTo(String value) {
            addCriterion("click_count <>", value, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountGreaterThan(String value) {
            addCriterion("click_count >", value, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountGreaterThanOrEqualTo(String value) {
            addCriterion("click_count >=", value, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountLessThan(String value) {
            addCriterion("click_count <", value, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountLessThanOrEqualTo(String value) {
            addCriterion("click_count <=", value, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountLike(String value) {
            addCriterion("click_count like", value, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountNotLike(String value) {
            addCriterion("click_count not like", value, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountIn(List<String> values) {
            addCriterion("click_count in", values, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountNotIn(List<String> values) {
            addCriterion("click_count not in", values, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountBetween(String value1, String value2) {
            addCriterion("click_count between", value1, value2, "clickCount");
            return (Criteria) this;
        }

        public Criteria andClickCountNotBetween(String value1, String value2) {
            addCriterion("click_count not between", value1, value2, "clickCount");
            return (Criteria) this;
        }

        public Criteria andLorIsNull() {
            addCriterion("lor is null");
            return (Criteria) this;
        }

        public Criteria andLorIsNotNull() {
            addCriterion("lor is not null");
            return (Criteria) this;
        }

        public Criteria andLorEqualTo(String value) {
            addCriterion("lor =", value, "lor");
            return (Criteria) this;
        }

        public Criteria andLorNotEqualTo(String value) {
            addCriterion("lor <>", value, "lor");
            return (Criteria) this;
        }

        public Criteria andLorGreaterThan(String value) {
            addCriterion("lor >", value, "lor");
            return (Criteria) this;
        }

        public Criteria andLorGreaterThanOrEqualTo(String value) {
            addCriterion("lor >=", value, "lor");
            return (Criteria) this;
        }

        public Criteria andLorLessThan(String value) {
            addCriterion("lor <", value, "lor");
            return (Criteria) this;
        }

        public Criteria andLorLessThanOrEqualTo(String value) {
            addCriterion("lor <=", value, "lor");
            return (Criteria) this;
        }

        public Criteria andLorLike(String value) {
            addCriterion("lor like", value, "lor");
            return (Criteria) this;
        }

        public Criteria andLorNotLike(String value) {
            addCriterion("lor not like", value, "lor");
            return (Criteria) this;
        }

        public Criteria andLorIn(List<String> values) {
            addCriterion("lor in", values, "lor");
            return (Criteria) this;
        }

        public Criteria andLorNotIn(List<String> values) {
            addCriterion("lor not in", values, "lor");
            return (Criteria) this;
        }

        public Criteria andLorBetween(String value1, String value2) {
            addCriterion("lor between", value1, value2, "lor");
            return (Criteria) this;
        }

        public Criteria andLorNotBetween(String value1, String value2) {
            addCriterion("lor not between", value1, value2, "lor");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andJianIsNull() {
            addCriterion("jian is null");
            return (Criteria) this;
        }

        public Criteria andJianIsNotNull() {
            addCriterion("jian is not null");
            return (Criteria) this;
        }

        public Criteria andJianEqualTo(String value) {
            addCriterion("jian =", value, "jian");
            return (Criteria) this;
        }

        public Criteria andJianNotEqualTo(String value) {
            addCriterion("jian <>", value, "jian");
            return (Criteria) this;
        }

        public Criteria andJianGreaterThan(String value) {
            addCriterion("jian >", value, "jian");
            return (Criteria) this;
        }

        public Criteria andJianGreaterThanOrEqualTo(String value) {
            addCriterion("jian >=", value, "jian");
            return (Criteria) this;
        }

        public Criteria andJianLessThan(String value) {
            addCriterion("jian <", value, "jian");
            return (Criteria) this;
        }

        public Criteria andJianLessThanOrEqualTo(String value) {
            addCriterion("jian <=", value, "jian");
            return (Criteria) this;
        }

        public Criteria andJianLike(String value) {
            addCriterion("jian like", value, "jian");
            return (Criteria) this;
        }

        public Criteria andJianNotLike(String value) {
            addCriterion("jian not like", value, "jian");
            return (Criteria) this;
        }

        public Criteria andJianIn(List<String> values) {
            addCriterion("jian in", values, "jian");
            return (Criteria) this;
        }

        public Criteria andJianNotIn(List<String> values) {
            addCriterion("jian not in", values, "jian");
            return (Criteria) this;
        }

        public Criteria andJianBetween(String value1, String value2) {
            addCriterion("jian between", value1, value2, "jian");
            return (Criteria) this;
        }

        public Criteria andJianNotBetween(String value1, String value2) {
            addCriterion("jian not between", value1, value2, "jian");
            return (Criteria) this;
        }

        public Criteria andTuotimeIsNull() {
            addCriterion("tuotime is null");
            return (Criteria) this;
        }

        public Criteria andTuotimeIsNotNull() {
            addCriterion("tuotime is not null");
            return (Criteria) this;
        }

        public Criteria andTuotimeEqualTo(String value) {
            addCriterion("tuotime =", value, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeNotEqualTo(String value) {
            addCriterion("tuotime <>", value, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeGreaterThan(String value) {
            addCriterion("tuotime >", value, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeGreaterThanOrEqualTo(String value) {
            addCriterion("tuotime >=", value, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeLessThan(String value) {
            addCriterion("tuotime <", value, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeLessThanOrEqualTo(String value) {
            addCriterion("tuotime <=", value, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeLike(String value) {
            addCriterion("tuotime like", value, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeNotLike(String value) {
            addCriterion("tuotime not like", value, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeIn(List<String> values) {
            addCriterion("tuotime in", values, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeNotIn(List<String> values) {
            addCriterion("tuotime not in", values, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeBetween(String value1, String value2) {
            addCriterion("tuotime between", value1, value2, "tuotime");
            return (Criteria) this;
        }

        public Criteria andTuotimeNotBetween(String value1, String value2) {
            addCriterion("tuotime not between", value1, value2, "tuotime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doautoaction
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 09 08:49:13 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doautoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}