package life.majiang.community.model;

public class Integral {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.user_name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.reason
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.gmt_creat
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long gmtCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.num
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.id
     *
     * @return the value of integral.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.id
     *
     * @param id the value for integral.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.user_id
     *
     * @return the value of integral.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.user_id
     *
     * @param userId the value for integral.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.user_name
     *
     * @return the value of integral.user_name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.user_name
     *
     * @param userName the value for integral.user_name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.reason
     *
     * @return the value of integral.reason
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.reason
     *
     * @param reason the value for integral.reason
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.gmt_creat
     *
     * @return the value of integral.gmt_creat
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.gmt_creat
     *
     * @param gmtCreat the value for integral.gmt_creat
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setGmtCreat(Long gmtCreat) {
        this.gmtCreat = gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.num
     *
     * @return the value of integral.num
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.num
     *
     * @param num the value for integral.num
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}