package life.majiang.community.model;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.msg
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.gmt_creat
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String gmtCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.readflag
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Integer readflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.user_id
     *
     * @return the value of notice.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.user_id
     *
     * @param userId the value for notice.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.msg
     *
     * @return the value of notice.msg
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.msg
     *
     * @param msg the value for notice.msg
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.gmt_creat
     *
     * @return the value of notice.gmt_creat
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.gmt_creat
     *
     * @param gmtCreat the value for notice.gmt_creat
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setGmtCreat(String gmtCreat) {
        this.gmtCreat = gmtCreat == null ? null : gmtCreat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.readflag
     *
     * @return the value of notice.readflag
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Integer getReadflag() {
        return readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.readflag
     *
     * @param readflag the value for notice.readflag
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setReadflag(Integer readflag) {
        this.readflag = readflag;
    }
}