package life.majiang.community.model;

import java.util.Date;

public class RedPacket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.id
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.user_id
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.amount
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.send_date
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private Date sendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.total
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.unit_amount
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private Long unitAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.stock
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.version
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redpacket.note
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.id
     *
     * @return the value of redpacket.id
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.id
     *
     * @param id the value for redpacket.id
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.user_id
     *
     * @return the value of redpacket.user_id
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.user_id
     *
     * @param userId the value for redpacket.user_id
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.amount
     *
     * @return the value of redpacket.amount
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.amount
     *
     * @param amount the value for redpacket.amount
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.send_date
     *
     * @return the value of redpacket.send_date
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public Date getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.send_date
     *
     * @param sendDate the value for redpacket.send_date
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.total
     *
     * @return the value of redpacket.total
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.total
     *
     * @param total the value for redpacket.total
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.unit_amount
     *
     * @return the value of redpacket.unit_amount
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public Long getUnitAmount() {
        return unitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.unit_amount
     *
     * @param unitAmount the value for redpacket.unit_amount
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setUnitAmount(Long unitAmount) {
        this.unitAmount = unitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.stock
     *
     * @return the value of redpacket.stock
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.stock
     *
     * @param stock the value for redpacket.stock
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.version
     *
     * @return the value of redpacket.version
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.version
     *
     * @param version the value for redpacket.version
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redpacket.note
     *
     * @return the value of redpacket.note
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redpacket.note
     *
     * @param note the value for redpacket.note
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}