package life.majiang.community.model;

public class Root {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root.id
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root.role
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root.function
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    private String function;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root.gmt_create
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root.gmt_modified
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root.intro
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root.id
     *
     * @return the value of root.id
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root.id
     *
     * @param id the value for root.id
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root.role
     *
     * @return the value of root.role
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root.role
     *
     * @param role the value for root.role
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root.function
     *
     * @return the value of root.function
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root.function
     *
     * @param function the value for root.function
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public void setFunction(String function) {
        this.function = function == null ? null : function.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root.gmt_create
     *
     * @return the value of root.gmt_create
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root.gmt_create
     *
     * @param gmtCreate the value for root.gmt_create
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root.gmt_modified
     *
     * @return the value of root.gmt_modified
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root.gmt_modified
     *
     * @param gmtModified the value for root.gmt_modified
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root.intro
     *
     * @return the value of root.intro
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root.intro
     *
     * @param intro the value for root.intro
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}