package life.majiang.community.model;

public class Tags {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.gmt_create
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.cla
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String cla;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.count
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.gmt_create
     *
     * @return the value of tags.gmt_create
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.gmt_create
     *
     * @param gmtCreate the value for tags.gmt_create
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.cla
     *
     * @return the value of tags.cla
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getCla() {
        return cla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.cla
     *
     * @param cla the value for tags.cla
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setCla(String cla) {
        this.cla = cla == null ? null : cla.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.count
     *
     * @return the value of tags.count
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.count
     *
     * @param count the value for tags.count
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}