package life.majiang.community.model;

public class Tuijian {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian.tab1
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String tab1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian.tab2
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String tab2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian.tab3
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private String tab3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian.id
     *
     * @return the value of tuijian.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian.id
     *
     * @param id the value for tuijian.id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian.tab1
     *
     * @return the value of tuijian.tab1
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getTab1() {
        return tab1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian.tab1
     *
     * @param tab1 the value for tuijian.tab1
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setTab1(String tab1) {
        this.tab1 = tab1 == null ? null : tab1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian.tab2
     *
     * @return the value of tuijian.tab2
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getTab2() {
        return tab2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian.tab2
     *
     * @param tab2 the value for tuijian.tab2
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setTab2(String tab2) {
        this.tab2 = tab2 == null ? null : tab2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian.tab3
     *
     * @return the value of tuijian.tab3
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getTab3() {
        return tab3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian.tab3
     *
     * @param tab3 the value for tuijian.tab3
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setTab3(String tab3) {
        this.tab3 = tab3 == null ? null : tab3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian.user_id
     *
     * @return the value of tuijian.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian.user_id
     *
     * @param userId the value for tuijian.user_id
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}