package life.majiang.community.model;

import java.util.ArrayList;
import java.util.List;

public class TuijianExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public TuijianExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTab1IsNull() {
            addCriterion("tab1 is null");
            return (Criteria) this;
        }

        public Criteria andTab1IsNotNull() {
            addCriterion("tab1 is not null");
            return (Criteria) this;
        }

        public Criteria andTab1EqualTo(String value) {
            addCriterion("tab1 =", value, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1NotEqualTo(String value) {
            addCriterion("tab1 <>", value, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1GreaterThan(String value) {
            addCriterion("tab1 >", value, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1GreaterThanOrEqualTo(String value) {
            addCriterion("tab1 >=", value, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1LessThan(String value) {
            addCriterion("tab1 <", value, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1LessThanOrEqualTo(String value) {
            addCriterion("tab1 <=", value, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1Like(String value) {
            addCriterion("tab1 like", value, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1NotLike(String value) {
            addCriterion("tab1 not like", value, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1In(List<String> values) {
            addCriterion("tab1 in", values, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1NotIn(List<String> values) {
            addCriterion("tab1 not in", values, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1Between(String value1, String value2) {
            addCriterion("tab1 between", value1, value2, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab1NotBetween(String value1, String value2) {
            addCriterion("tab1 not between", value1, value2, "tab1");
            return (Criteria) this;
        }

        public Criteria andTab2IsNull() {
            addCriterion("tab2 is null");
            return (Criteria) this;
        }

        public Criteria andTab2IsNotNull() {
            addCriterion("tab2 is not null");
            return (Criteria) this;
        }

        public Criteria andTab2EqualTo(String value) {
            addCriterion("tab2 =", value, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2NotEqualTo(String value) {
            addCriterion("tab2 <>", value, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2GreaterThan(String value) {
            addCriterion("tab2 >", value, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2GreaterThanOrEqualTo(String value) {
            addCriterion("tab2 >=", value, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2LessThan(String value) {
            addCriterion("tab2 <", value, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2LessThanOrEqualTo(String value) {
            addCriterion("tab2 <=", value, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2Like(String value) {
            addCriterion("tab2 like", value, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2NotLike(String value) {
            addCriterion("tab2 not like", value, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2In(List<String> values) {
            addCriterion("tab2 in", values, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2NotIn(List<String> values) {
            addCriterion("tab2 not in", values, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2Between(String value1, String value2) {
            addCriterion("tab2 between", value1, value2, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab2NotBetween(String value1, String value2) {
            addCriterion("tab2 not between", value1, value2, "tab2");
            return (Criteria) this;
        }

        public Criteria andTab3IsNull() {
            addCriterion("tab3 is null");
            return (Criteria) this;
        }

        public Criteria andTab3IsNotNull() {
            addCriterion("tab3 is not null");
            return (Criteria) this;
        }

        public Criteria andTab3EqualTo(String value) {
            addCriterion("tab3 =", value, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3NotEqualTo(String value) {
            addCriterion("tab3 <>", value, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3GreaterThan(String value) {
            addCriterion("tab3 >", value, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3GreaterThanOrEqualTo(String value) {
            addCriterion("tab3 >=", value, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3LessThan(String value) {
            addCriterion("tab3 <", value, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3LessThanOrEqualTo(String value) {
            addCriterion("tab3 <=", value, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3Like(String value) {
            addCriterion("tab3 like", value, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3NotLike(String value) {
            addCriterion("tab3 not like", value, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3In(List<String> values) {
            addCriterion("tab3 in", values, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3NotIn(List<String> values) {
            addCriterion("tab3 not in", values, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3Between(String value1, String value2) {
            addCriterion("tab3 between", value1, value2, "tab3");
            return (Criteria) this;
        }

        public Criteria andTab3NotBetween(String value1, String value2) {
            addCriterion("tab3 not between", value1, value2, "tab3");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuijian
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 09 08:49:13 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}