package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Accesstoken;
import life.majiang.community.model.AccesstokenExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AccesstokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    long countByExample(AccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int deleteByExample(AccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int insert(Accesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int insertSelective(Accesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    List<Accesstoken> selectByExampleWithRowbounds(AccesstokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    List<Accesstoken> selectByExample(AccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    Accesstoken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Accesstoken record, @Param("example") AccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByExample(@Param("record") Accesstoken record, @Param("example") AccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByPrimaryKeySelective(Accesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accesstoken
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByPrimaryKey(Accesstoken record);
}