package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Autoaction;
import life.majiang.community.model.AutoactionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AutoactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    long countByExample(AutoactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int deleteByExample(AutoactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int insert(Autoaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int insertSelective(Autoaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    List<Autoaction> selectByExampleWithRowbounds(AutoactionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    List<Autoaction> selectByExample(AutoactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    Autoaction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Autoaction record, @Param("example") AutoactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByExample(@Param("record") Autoaction record, @Param("example") AutoactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByPrimaryKeySelective(Autoaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autoaction
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByPrimaryKey(Autoaction record);
}