package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Questiongood;
import life.majiang.community.model.QuestiongoodExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QuestiongoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    long countByExample(QuestiongoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int deleteByExample(QuestiongoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int insert(Questiongood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int insertSelective(Questiongood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    List<Questiongood> selectByExampleWithRowbounds(QuestiongoodExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    List<Questiongood> selectByExample(QuestiongoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    Questiongood selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Questiongood record, @Param("example") QuestiongoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByExample(@Param("record") Questiongood record, @Param("example") QuestiongoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByPrimaryKeySelective(Questiongood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiongood
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByPrimaryKey(Questiongood record);
}