package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.RedPacket;
import life.majiang.community.model.RedPacketExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RedPacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    long countByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int deleteByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int insert(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int insertSelective(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    List<RedPacket> selectByExampleWithRowbounds(RedPacketExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    List<RedPacket> selectByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    RedPacket selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") RedPacket record, @Param("example") RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int updateByExample(@Param("record") RedPacket record, @Param("example") RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int updateByPrimaryKeySelective(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int updateByPrimaryKey(RedPacket record);
}