package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Root;
import life.majiang.community.model.RootExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RootMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    long countByExample(RootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    int deleteByExample(RootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    int insert(Root record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    int insertSelective(Root record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    List<Root> selectByExampleWithRowbounds(RootExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    List<Root> selectByExample(RootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    Root selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Root record, @Param("example") RootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    int updateByExample(@Param("record") Root record, @Param("example") RootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    int updateByPrimaryKeySelective(Root record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Wed Jul 22 16:47:03 CST 2020
     */
    int updateByPrimaryKey(Root record);
}