package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.Tuijian;
import life.majiang.community.model.TuijianExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TuijianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    long countByExample(TuijianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int deleteByExample(TuijianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int insert(Tuijian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int insertSelective(Tuijian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    List<Tuijian> selectByExampleWithRowbounds(TuijianExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    List<Tuijian> selectByExample(TuijianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    Tuijian selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Tuijian record, @Param("example") TuijianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByExample(@Param("record") Tuijian record, @Param("example") TuijianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByPrimaryKeySelective(Tuijian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuijian
     *
     * @mbg.generated Wed Sep 09 08:49:13 CST 2020
     */
    int updateByPrimaryKey(Tuijian record);
}