package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.UserRedPacket;
import life.majiang.community.model.UserRedPacketExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserRedPacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    long countByExample(UserRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int deleteByExample(UserRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int insert(UserRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int insertSelective(UserRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    List<UserRedPacket> selectByExampleWithRowbounds(UserRedPacketExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    List<UserRedPacket> selectByExample(UserRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    UserRedPacket selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserRedPacket record, @Param("example") UserRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int updateByExample(@Param("record") UserRedPacket record, @Param("example") UserRedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int updateByPrimaryKeySelective(UserRedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userredpacket
     *
     * @mbg.generated Wed Aug 19 09:45:20 CST 2020
     */
    int updateByPrimaryKey(UserRedPacket record);
}